import type { Metadata } from "next";
import { Zain } from "next/font/google";
import "./globals.css";
import "./Portfolio.css";

const zain = Zain({
  variable: "--font-zain",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${zain.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(){
              try{
                var t = localStorage.getItem('site-theme');
                if(t==='light' || t==='dark'){
                  document.documentElement.setAttribute('data-theme', t);
                } else {
                  // default to dark when no preference
                  document.documentElement.setAttribute('data-theme', 'dark');
                }
              }catch(e){}
            })();
          `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
